@echo off  
echo "Cleaning up..."  
call npx hexo clean || echo Failed to clean up. Continuing...  
echo "Generating..."  
call npx hexo g || echo Failed to generate. Continuing...  
echo "Deploying..."  
call npx hexo d || echo Failed to deploy. Continuing...  
echo "Done!"